{% set name = "oifits" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11c13096f234f3f0b6b2f382da840eac2360ed1231b166225e7dd9a303161810

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - astropy
    - numpy

test:
  imports:
    - oifits

about:
  home: http://github.com/shreyasbapat/python-oifits
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'Python Module to work with OIFITS '
  description: |
    python-oifits is the python package for dealing with
    Event Horizons Telescope Data. The Data is in infamous
    OIFITS format. Which is too complex to parse everytime
    when applying any machine learning or deep learning model
    on the VLBI Data. The module provides easy access to all
    the data that is in the OIFITS file.
  doc_url: http://oifits.vlbi.software/
  dev_url: https://github.com/shreyasbapat/python-oifits

extra:
  recipe-maintainers:
    - shreyasbapat
