travis:
  secure:
    BINSTAR_TOKEN: hagRrTiwD3BJwgaFOCz1MuAcD9M3outGr0JFwKheKti2Ds6Ub+56mO3HCEYIVCF466wKQcvwqE8Zt/gqc7uDYRPyBU5TbzGxHIbJASKOgTFW8YQ2j0uXmlSzwIcfgPS0HaHF8qaOpebo9rSgygUYc9c7wUitr98Q1R1OeuTeZBC/rAdGvpt+nW3xwZX5f9mAZ7XPRgsKPMm3LsHegnCOTClB+yU/ep1Z9xKbvjtEhxtTtjnb1+jr9e7tiIkTxZjQzbjbQ81O4a7UEJq3yQjV8nN6RDBtNTvX8Er2MKZTrgVqFEXlQEPn+cxxGl+DFuma5AkkZVVDr4FcKMfVcQbgebcTyooTX17tgKjEoXbLU6zfteJPXv++WanENj+sR1fC8CtKAoG1VvSCBFzAvkDskY4kAAmTXFYp68jrhiLpVcntr10J0ZpE6hX0bqcjVFIE0lFridy0MnmdLBhTOvqVjPguTLdfQjmMTmI52xM+U9MKARN2GcOPHvlNWBT4jayve7Y4TPAjWrPiYp7V3EFeIBVBeOGRgtZeW58yfMKNvUSJRiY3s390YCw6LxP009iUC9HPC8xfRK/FWvvJZ57EMJsIMM9OXhDMsOCbMpaTucSCSOy6sNZSBxHGRV3SI8c/EC6Z10sP8whEsTDpn51dY0eH8ewN+QCM32R5vE99r14=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
